---
fail_fast: false
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: ruff-format
        types_or: [ python, pyi ]
        description: "Run 'ruff format' for extremely fast Python formatting"
        entry: ruff format --force-exclude
        language: python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies:
          - "pydantic>=2.10.5"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-builtin-literals
      - id: check-shebang-scripts-are-executable
        types: [file, bash]
      - id: end-of-file-fixer
      - id: debug-statements
      - id: mixed-line-ending
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: trailing-whitespace
        exclude: README.md
      - id: check-added-large-files
        args: ["--maxkb=2000"]
